### ISSUE TITLE
[Tracking] Design Tokens

### ISSUE THREAD

**Issue by laurenbarker** [cockroachdb/ui#27]
## What
Add design-tokens package to the UI Repo.

## Why
Ensure brand styles (colors, spacing, typography, etc.) can be included in all of our user facing apps while maintaining a single source of truth.

## Phase 1
- [ ] Add design-tokens package to the UI Repo
- [ ] Manually add our brand styles in JSON format in a similar format to base.json in the prototype (link in design doc)
    * To begin with, the brand styles to include are the variables currently defined in CC
    * Each category of token (color, grid, etc.) will require a different level of organization. Wunderzin’s base.json provides some examples of tokens that have many variations.
- [ ] Configure Style Dictionary to output our brand styles in three formats: SASS, JS, Stylus
    * SCSS and JS are [pre-defined style dictionary formats](https://amzn.github.io/style-dictionary/#/formats?id=pre-defined-formats) but Stylus would require a [custom formatter](https://amzn.github.io/style-dictionary/#/formats?id=creating-formats)
    * The high level categories can be split into separate files. Wunderzin’s [web build](https://github.com/PavelLaptev/wunderzin/tree/master/style-dictionary/build/web) provides an example.
- [ ] Publish the design-tokens package to npm
- [ ] Consume the npm package in CC, shared component library, and wherever else the brand styles are needed

## Phase 2
- [ ] generate token from Figma (see design doc)
