### ISSUE TITLE
[Tracking] CONTRIBUTING to the UI Repo

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/ui#38]
_This is a working issue to organize efforts around contributor documentation. Feel free to leave comments or suggestions._

## Sections under consideration
- [ ] Introduction (what and why is this?)
- [ ] Contributor setup (cloning, nodejs, and lerna setup)
- [ ] Code Style (eslint setup, react patterns, directory and file conventions)
- [ ] PR checklist (setting expectation for the PR template)
- [ ] Writing stories (working with storybook, requirements for good stories)
- [ ] Writing tests
- [ ] Publishing (working with Lerna, npm, and github)
- [ ] Upgrading Dependencies (how to upgrade, respond to security warnings, etc)
- [ ] Checking out PR for code and design review (#63)
- [ ] Package Directory (what lives in this repo with links to sub-documentation)
- [ ] Label index (How to label things, expectations for finding issues and who reviews them, how things work, etc) 👈 _Maybe this belongs in Introduction?_
